# Generated by Django 6.1 on 2026-08-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointment_unique_doctor_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('RECEPTIONIST', 'Receptionist'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('ACCOUNTANT', 'Accountant')], default='PATIENT', max_length=30),
        ),
    ]
